//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUpSchoolProject.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UpSchoolDbPortfolioEntities : DbContext
    {
        public UpSchoolDbPortfolioEntities()
            : base("name=UpSchoolDbPortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_About> TBL_About { get; set; }
        public virtual DbSet<TBL_Feature> TBL_Feature { get; set; }
        public virtual DbSet<TBL_Services> TBL_Services { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Testimonial> TBL_Testimonial { get; set; }
        public virtual DbSet<TBL_Member> TBL_Member { get; set; }
        public virtual DbSet<TBL_Message> TBL_Message { get; set; }
        public virtual DbSet<TBL_PROJECT> TBL_PROJECT { get; set; }
    }
}
